---
title: "WRST Caribou Results QC check, database to reported results"

description: "Generates a population estimate corrected for sightability (in those survey collecting sightability information (Seen is not NULL)). 

Change the parameter SurveyName to a valid SurveyName from the WRST_Caribou database. There is a code
snippet below that you can uncomment to get a list of valid survey names.

"

author: "SDMiller"
date: "`r sys.date'"
output: html_document
---

```{r setup, include=FALSE}
# options(download.file.method = "wininet")

Herd = 'Chisana'

knitr::opts_chunk$set(echo = TRUE)

# Setup
options(knitr.kable.NA = '')
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(RODBC)
library(tidyverse)
#devtools::install_github("jfieberg/SightabilityModel", dependencies = TRUE, build_vignettes = TRUE)
library(SightabilityModel)

# Database connection string
Connection =  odbcDriverConnect('Driver={SQL Server};Server=inpyugamsvm01\\nuna;Database=WRST_Caribou;Trusted_connection=yes')

# Function that returns a data frame from an SQL query on the database
# SQL: A valid SQL query
GetDataFrame <- function(SQL) { # create a function with the name my_function
  DF = sqlQuery(Connection,SQL)
  return(DF)
}

```



# Spring Population Estimate, `r Herd`

```{r echo=FALSE}
# Get the summarized data for the comp count survey into a data frame
Sql = paste("
SELECT r.Year, r.Herd
, ISNULL(r.SpringPopulationEstimate,0) as SpringPopulationEstimate
, r.SpringPctCow
, r.SpringPctCalves
, r.SpringPctBulls
, r.SpringCalvesPer100Cows
, r.SpringBullsPer100Cows
, r.FallPopulationEstimate
, r.FallCows
, r.FallCalves
, r.FallBull
, r.FallTotal
, r.FallCalvesPer100Cows
, r.FallBullsPer100Cows
, r.FallPctCow
, r.FallPctCalves
, r.FallPctBulls
, r.FallSampleSize
--, rpt.Citation
--, rpt.SourceURL
, r.ResultID
, rpt.SourceID
FROM     Reports AS rpt INNER JOIN
    Results AS r ON rpt.SourceID = r.SourceID
WHERE (r.Herd = '",Herd,"')
ORDER BY r.Year            
            ",sep="")
DF = GetDataFrame(Sql)
kable(DF)


GraphTitle = paste("Population size, ",Herd," caribou herd",sep="")
ggplot(data=DF,aes(x = Year)) +
  geom_line(aes(y = FallPopulationEstimate,colour="black"),size=1, linetype='solid') +
  geom_line(aes(y = SpringPopulationEstimate,colour="darkgray"), size=1, linetype='solid')  + 
  xlab("Year") +
  ylab("Estimate") +
  ggtitle(GraphTitle) +
  #scale_color_manual(labels = c("Bulls:100 cows", "Calves:100 cows"), values = c("black", "darkgray"))  + 
  theme_classic()


# Plot the calf/bull/cow ratios
plot(DF$Year, DF$FallPopulationEstimate, type = "l", xlab = "Year", ylab = "SpringPopulationEstimate")              
#lines(DF$Year, DF$FallPopulationEstimate, type = "l", col = "red")                   # Add second line
#legend("topleft",legend = c("Bulls:100 cows", "Calves:100 cows"), col = c("black", "red"),       lty = 1)




```

